### ISSUE TITLE
about the time points

### ISSUE THREAD

**Issue by mengliu1991** [LisaAnne/LocalizingMoments#2]
Hi,
  In the .json file, each video has more than one time points. For example, "video": "26292851@N04_4253489686_265c3c8051.m4v" has 7 time points: "times": [[4, 4], [4, 4], [0, 0], [4, 4], [0, 0], [0, 0], [4, 4]]. I wanna to know which one you choose as ground truth when training your model? 
  And how to evaluate the testing result with these time points?

**Comment by LisaAnne** [comment]
Hi there -

There is eval code in the repo:
https://github.com/LisaAnne/LocalizingMoments/blob/master/eval.py.

I randomly chose a time point of the provided time points.  This particular
example contains a bit more disagreement than usual.

**Comment by LisaAnne** [comment]
Hi there -

There is eval code in the repo: https://github.com/LisaAnne/LocalizingMoments/blob/master/eval.py.

I randomly chose a time point of the provided time points.  Usually videos have four time points; this has seven because it was put on AMT twice because my batches need to be divisible by 4 (there are a few examples like that).

**Comment by ClaraBing** [comment]
Hi,
May I ask if the eval code is still available?
Thank you!
